// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppInfo {
    "version": string;
    "repositoryUrl": string;
    "detectedOs": string;
    "installMethod": string;
    "configDirectory": string;
    "configFile": string;
    "executablePath": string;

    /** Creates a new AppInfo instance. */
    constructor($$source: Partial<AppInfo> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("repositoryUrl" in $$source)) {
            this["repositoryUrl"] = "";
        }
        if (!("detectedOs" in $$source)) {
            this["detectedOs"] = "";
        }
        if (!("installMethod" in $$source)) {
            this["installMethod"] = "";
        }
        if (!("configDirectory" in $$source)) {
            this["configDirectory"] = "";
        }
        if (!("configFile" in $$source)) {
            this["configFile"] = "";
        }
        if (!("executablePath" in $$source)) {
            this["executablePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AppInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppInfo($$parsedSource as Partial<AppInfo>);
    }
}
