// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as prayer$0 from "../prayer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class AppInfo {
    "version": string;
    "repositoryUrl": string;
    "detectedOs": string;
    "installMethod": string;
    "configDirectory": string;
    "configFile": string;
    "executablePath": string;

    /** Creates a new AppInfo instance. */
    constructor($$source: Partial<AppInfo> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("repositoryUrl" in $$source)) {
            this["repositoryUrl"] = "";
        }
        if (!("detectedOs" in $$source)) {
            this["detectedOs"] = "";
        }
        if (!("installMethod" in $$source)) {
            this["installMethod"] = "";
        }
        if (!("configDirectory" in $$source)) {
            this["configDirectory"] = "";
        }
        if (!("configFile" in $$source)) {
            this["configFile"] = "";
        }
        if (!("executablePath" in $$source)) {
            this["executablePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AppInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppInfo($$parsedSource as Partial<AppInfo>);
    }
}

/**
 * DebugTimeInfo exposes the backend's current time data.
 */
export class DebugTimeInfo {
    "nowRFC3339": string;
    "clock": string;
    "timezone": string;
    "offset": string;

    /** Creates a new DebugTimeInfo instance. */
    constructor($$source: Partial<DebugTimeInfo> = {}) {
        if (!("nowRFC3339" in $$source)) {
            this["nowRFC3339"] = "";
        }
        if (!("clock" in $$source)) {
            this["clock"] = "";
        }
        if (!("timezone" in $$source)) {
            this["timezone"] = "";
        }
        if (!("offset" in $$source)) {
            this["offset"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DebugTimeInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DebugTimeInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DebugTimeInfo($$parsedSource as Partial<DebugTimeInfo>);
    }
}

export class QuranBookmark {
    "id": string;
    "url": string;
    "note": string;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new QuranBookmark instance. */
    constructor($$source: Partial<QuranBookmark> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("note" in $$source)) {
            this["note"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuranBookmark instance from a string or object.
     */
    static createFrom($$source: any = {}): QuranBookmark {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuranBookmark($$parsedSource as Partial<QuranBookmark>);
    }
}

export class QuranData {
    "bookmarks": QuranBookmark[];
    "notes": QuranNote[];

    /** Creates a new QuranData instance. */
    constructor($$source: Partial<QuranData> = {}) {
        if (!("bookmarks" in $$source)) {
            this["bookmarks"] = [];
        }
        if (!("notes" in $$source)) {
            this["notes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuranData instance from a string or object.
     */
    static createFrom($$source: any = {}): QuranData {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bookmarks" in $$parsedSource) {
            $$parsedSource["bookmarks"] = $$createField0_0($$parsedSource["bookmarks"]);
        }
        if ("notes" in $$parsedSource) {
            $$parsedSource["notes"] = $$createField1_0($$parsedSource["notes"]);
        }
        return new QuranData($$parsedSource as Partial<QuranData>);
    }
}

export class QuranNote {
    "id": string;
    "title": string;
    "body": string;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new QuranNote instance. */
    constructor($$source: Partial<QuranNote> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuranNote instance from a string or object.
     */
    static createFrom($$source: any = {}): QuranNote {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuranNote($$parsedSource as Partial<QuranNote>);
    }
}

/**
 * ReminderDebugEntry describes a scheduled reminder time for debugging.
 */
export class ReminderDebugEntry {
    "prayerName": string;
    "state": string;
    "scheduledTime": string;
    "offsetMinutes": number;
    "enabled": boolean;
    "deltaSeconds": number;
    "isFuture": boolean;

    /** Creates a new ReminderDebugEntry instance. */
    constructor($$source: Partial<ReminderDebugEntry> = {}) {
        if (!("prayerName" in $$source)) {
            this["prayerName"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("scheduledTime" in $$source)) {
            this["scheduledTime"] = "";
        }
        if (!("offsetMinutes" in $$source)) {
            this["offsetMinutes"] = 0;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("deltaSeconds" in $$source)) {
            this["deltaSeconds"] = 0;
        }
        if (!("isFuture" in $$source)) {
            this["isFuture"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReminderDebugEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ReminderDebugEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReminderDebugEntry($$parsedSource as Partial<ReminderDebugEntry>);
    }
}

export class ReminderTestSnapshot {
    "timezone": string;
    "currentTime": string;
    "simulatedTime": string;
    "prayerName": string;
    "prayerTime": string;
    "offsetSeconds": number;
    "state": string;
    "minutesLeft": number;
    "nextPrayerName": string;
    "nextPrayerTime": string;
    "schedule": { [_ in string]?: string };

    /** Creates a new ReminderTestSnapshot instance. */
    constructor($$source: Partial<ReminderTestSnapshot> = {}) {
        if (!("timezone" in $$source)) {
            this["timezone"] = "";
        }
        if (!("currentTime" in $$source)) {
            this["currentTime"] = "";
        }
        if (!("simulatedTime" in $$source)) {
            this["simulatedTime"] = "";
        }
        if (!("prayerName" in $$source)) {
            this["prayerName"] = "";
        }
        if (!("prayerTime" in $$source)) {
            this["prayerTime"] = "";
        }
        if (!("offsetSeconds" in $$source)) {
            this["offsetSeconds"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("minutesLeft" in $$source)) {
            this["minutesLeft"] = 0;
        }
        if (!("nextPrayerName" in $$source)) {
            this["nextPrayerName"] = "";
        }
        if (!("nextPrayerTime" in $$source)) {
            this["nextPrayerTime"] = "";
        }
        if (!("schedule" in $$source)) {
            this["schedule"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReminderTestSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): ReminderTestSnapshot {
        const $$createField10_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("schedule" in $$parsedSource) {
            $$parsedSource["schedule"] = $$createField10_0($$parsedSource["schedule"]);
        }
        return new ReminderTestSnapshot($$parsedSource as Partial<ReminderTestSnapshot>);
    }
}

export class UpdateInfo {
    "currentVersion": string;
    "latestVersion": string;
    "releaseUrl": string;
    "hasUpdate": boolean;
    "installMethod": string;
    "updateTitle": string;
    "updateDetail": string;
    "actionLabel": string;
    "updateCommand": string;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("releaseUrl" in $$source)) {
            this["releaseUrl"] = "";
        }
        if (!("hasUpdate" in $$source)) {
            this["hasUpdate"] = false;
        }
        if (!("installMethod" in $$source)) {
            this["installMethod"] = "";
        }
        if (!("updateTitle" in $$source)) {
            this["updateTitle"] = "";
        }
        if (!("updateDetail" in $$source)) {
            this["updateDetail"] = "";
        }
        if (!("actionLabel" in $$source)) {
            this["actionLabel"] = "";
        }
        if (!("updateCommand" in $$source)) {
            this["updateCommand"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

export class WorldPrayerCitySummary {
    "city": settings$0.WorldPrayerCity;
    "offsetSeconds": number;
    "currentTime": time$0.Time;
    "nextPrayer": prayer$0.NextPrayerInfo;
    "today": prayer$0.DaySchedule;

    /** Creates a new WorldPrayerCitySummary instance. */
    constructor($$source: Partial<WorldPrayerCitySummary> = {}) {
        if (!("city" in $$source)) {
            this["city"] = (new settings$0.WorldPrayerCity());
        }
        if (!("offsetSeconds" in $$source)) {
            this["offsetSeconds"] = 0;
        }
        if (!("currentTime" in $$source)) {
            this["currentTime"] = null;
        }
        if (!("nextPrayer" in $$source)) {
            this["nextPrayer"] = (new prayer$0.NextPrayerInfo());
        }
        if (!("today" in $$source)) {
            this["today"] = (new prayer$0.DaySchedule());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorldPrayerCitySummary instance from a string or object.
     */
    static createFrom($$source: any = {}): WorldPrayerCitySummary {
        const $$createField0_0 = $$createType5;
        const $$createField3_0 = $$createType6;
        const $$createField4_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("city" in $$parsedSource) {
            $$parsedSource["city"] = $$createField0_0($$parsedSource["city"]);
        }
        if ("nextPrayer" in $$parsedSource) {
            $$parsedSource["nextPrayer"] = $$createField3_0($$parsedSource["nextPrayer"]);
        }
        if ("today" in $$parsedSource) {
            $$parsedSource["today"] = $$createField4_0($$parsedSource["today"]);
        }
        return new WorldPrayerCitySummary($$parsedSource as Partial<WorldPrayerCitySummary>);
    }
}

// Private type creation functions
const $$createType0 = QuranBookmark.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = QuranNote.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = settings$0.WorldPrayerCity.createFrom;
const $$createType6 = prayer$0.NextPrayerInfo.createFrom;
const $$createType7 = prayer$0.DaySchedule.createFrom;
