// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-facing bridge between the frontend and the Go services.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as geonames$0 from "../geonames/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hijri$0 from "../hijri/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as location$0 from "../location/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notification$0 from "../notification/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as prayer$0 from "../prayer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scheduler$0 from "../scheduler/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckForUpdates(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(2121986746).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CheckNativeNotificationPermission(): $CancellablePromise<boolean> {
    return $Call.ByID(2633779010);
}

export function CloseTestReminderWindow(): $CancellablePromise<void> {
    return $Call.ByID(2475091271);
}

export function DetectLocation(): $CancellablePromise<location$0.Location> {
    return $Call.ByID(3572912391).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DismissReminder(): $CancellablePromise<void> {
    return $Call.ByID(2073427023);
}

export function DismissTestReminder(): $CancellablePromise<void> {
    return $Call.ByID(2069685327);
}

export function EmitReminderInfo(): $CancellablePromise<void> {
    return $Call.ByID(3137520330);
}

export function EmitTestReminderInfo(): $CancellablePromise<void> {
    return $Call.ByID(1725356406);
}

export function ExportRangeToCSV(startDate: string, endDate: string, outputPath: string): $CancellablePromise<void> {
    return $Call.ByID(2450987025, startDate, endDate, outputPath);
}

export function ExportRangeToExcel(startDate: string, endDate: string, outputPath: string): $CancellablePromise<void> {
    return $Call.ByID(486373810, startDate, endDate, outputPath);
}

export function ExportToCSV($0: number, $1: number, startDate: string, endDate: string, outputPath: string): $CancellablePromise<void> {
    return $Call.ByID(3125859884, $0, $1, startDate, endDate, outputPath);
}

export function ExportToExcel($0: number, $1: number, startDate: string, endDate: string, outputPath: string): $CancellablePromise<void> {
    return $Call.ByID(3627630511, $0, $1, startDate, endDate, outputPath);
}

export function GetAppInfo(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(4277767660).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetCardinalDirection(bearing: number): $CancellablePromise<string> {
    return $Call.ByID(3395061602, bearing);
}

export function GetCurrentTime(): $CancellablePromise<string> {
    return $Call.ByID(160623751);
}

/**
 * GetDebugTimeInfo returns the backend's current time and timezone info.
 */
export function GetDebugTimeInfo(): $CancellablePromise<$models.DebugTimeInfo> {
    return $Call.ByID(1016560685).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetGeonamesInfo(): $CancellablePromise<geonames$0.DataInfo> {
    return $Call.ByID(498202194).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetHijriDateRange(startDate: string, endDate: string): $CancellablePromise<hijri$0.CalendarDay[]> {
    return $Call.ByID(709292810, startDate, endDate).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetHijriForDate(dateStr: string): $CancellablePromise<hijri$0.HijriDate> {
    return $Call.ByID(2391955296, dateStr).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetLocation(): $CancellablePromise<location$0.Location> {
    return $Call.ByID(3694251338).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetMonthHijriDates(year: number, month: number): $CancellablePromise<hijri$0.CalendarDay[]> {
    return $Call.ByID(3210272434, year, month).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetMonthSchedule(year: number, month: number): $CancellablePromise<prayer$0.DaySchedule[]> {
    return $Call.ByID(107226984, year, month).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetNextPrayer(): $CancellablePromise<prayer$0.NextPrayerInfo> {
    return $Call.ByID(3689796055).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetQiblaDirection(): $CancellablePromise<number> {
    return $Call.ByID(2384189501);
}

export function GetQiblaDirectionFor(lat: number, lon: number): $CancellablePromise<number> {
    return $Call.ByID(4286043432, lat, lon);
}

export function GetQuranData(): $CancellablePromise<$models.QuranData> {
    return $Call.ByID(2354148668).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetReminderDebugSchedule returns today's reminder schedule with relative timing info.
 */
export function GetReminderDebugSchedule(): $CancellablePromise<$models.ReminderDebugEntry[]> {
    return $Call.ByID(1456279359).then(($result: any) => {
        return $$createType13($result);
    });
}

export function GetReminderInfo(): $CancellablePromise<notification$0.ReminderInfo | null> {
    return $Call.ByID(3787072775).then(($result: any) => {
        return $$createType15($result);
    });
}

export function GetReminderState(): $CancellablePromise<notification$0.ReminderInfo | null> {
    return $Call.ByID(479880836).then(($result: any) => {
        return $$createType15($result);
    });
}

export function GetReminderTestSnapshot(prayerName: string, offsetSeconds: number, timezone: string): $CancellablePromise<$models.ReminderTestSnapshot> {
    return $Call.ByID(2916182751, prayerName, offsetSeconds, timezone).then(($result: any) => {
        return $$createType16($result);
    });
}

export function GetScheduleForDate(dateStr: string): $CancellablePromise<prayer$0.DaySchedule> {
    return $Call.ByID(2969710027, dateStr).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetScheduleRange(startDate: string, endDate: string): $CancellablePromise<prayer$0.DaySchedule[]> {
    return $Call.ByID(2289686101, startDate, endDate).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetSettings(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(1855413340).then(($result: any) => {
        return $$createType17($result);
    });
}

export function GetTestReminderInfo(): $CancellablePromise<notification$0.ReminderInfo | null> {
    return $Call.ByID(904619519).then(($result: any) => {
        return $$createType15($result);
    });
}

export function GetTestReminderState(): $CancellablePromise<notification$0.ReminderInfo | null> {
    return $Call.ByID(3437621020).then(($result: any) => {
        return $$createType15($result);
    });
}

export function GetTimezones(): $CancellablePromise<string[]> {
    return $Call.ByID(3432876695).then(($result: any) => {
        return $$createType18($result);
    });
}

export function GetTodayHijri(): $CancellablePromise<hijri$0.HijriDate> {
    return $Call.ByID(4192043028).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetTodaySchedule(): $CancellablePromise<prayer$0.DaySchedule> {
    return $Call.ByID(1655258847).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetWorldPrayerTimes(cities: settings$0.WorldPrayerCity[]): $CancellablePromise<$models.WorldPrayerCitySummary[]> {
    return $Call.ByID(4281561666, cities).then(($result: any) => {
        return $$createType20($result);
    });
}

export function OpenConfigLocation(): $CancellablePromise<void> {
    return $Call.ByID(1230630530);
}

export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(3112046108, url);
}

export function PlayAdhan(isFajr: boolean): $CancellablePromise<void> {
    return $Call.ByID(40014119, isFajr);
}

export function ReadTextFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(1179436650, path);
}

export function RequestNativeNotificationPermission(): $CancellablePromise<boolean> {
    return $Call.ByID(853643315);
}

export function ResetSettings(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(1081576467).then(($result: any) => {
        return $$createType17($result);
    });
}

export function ResizeReminderWindow(state: string, isTest: boolean): $CancellablePromise<void> {
    return $Call.ByID(3387659901, state, isTest);
}

export function SaveBase64File(outputPath: string, base64Data: string): $CancellablePromise<void> {
    return $Call.ByID(2960550107, outputPath, base64Data);
}

export function SaveQuranData(payload: $models.QuranData): $CancellablePromise<void> {
    return $Call.ByID(4069193973, payload);
}

export function SaveSettings(cfg: settings$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(1563075575, cfg);
}

export function SearchCities(query: string, limit: number): $CancellablePromise<geonames$0.City[]> {
    return $Call.ByID(2775474700, query, limit).then(($result: any) => {
        return $$createType22($result);
    });
}

export function SearchTimezones(query: string, limit: number): $CancellablePromise<string[]> {
    return $Call.ByID(3774805361, query, limit).then(($result: any) => {
        return $$createType18($result);
    });
}

export function SetManualLocation(loc: location$0.Location): $CancellablePromise<void> {
    return $Call.ByID(67415564, loc);
}

export function SetRuntimeServices(notifSvc: notification$0.Service | null, schedulerSvc: scheduler$0.Service | null): $CancellablePromise<void> {
    return $Call.ByID(833235791, notifSvc, schedulerSvc);
}

export function StopAdhan(): $CancellablePromise<void> {
    return $Call.ByID(2479816481);
}

export function SyncReminderTestWindow(prayerName: string, offsetSeconds: number, timezone: string, live: boolean): $CancellablePromise<$models.ReminderTestSnapshot> {
    return $Call.ByID(3232718466, prayerName, offsetSeconds, timezone, live).then(($result: any) => {
        return $$createType16($result);
    });
}

export function TriggerReminderTest(prayerName: string, offsetSeconds: number, timezone: string, live: boolean): $CancellablePromise<$models.ReminderTestSnapshot> {
    return $Call.ByID(2478091023, prayerName, offsetSeconds, timezone, live).then(($result: any) => {
        return $$createType16($result);
    });
}

export function UpdateGeonamesData(): $CancellablePromise<geonames$0.DataInfo> {
    return $Call.ByID(1680012853).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = location$0.Location.createFrom;
const $$createType2 = $models.AppInfo.createFrom;
const $$createType3 = $models.DebugTimeInfo.createFrom;
const $$createType4 = geonames$0.DataInfo.createFrom;
const $$createType5 = hijri$0.CalendarDay.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = hijri$0.HijriDate.createFrom;
const $$createType8 = prayer$0.DaySchedule.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = prayer$0.NextPrayerInfo.createFrom;
const $$createType11 = $models.QuranData.createFrom;
const $$createType12 = $models.ReminderDebugEntry.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = notification$0.ReminderInfo.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $models.ReminderTestSnapshot.createFrom;
const $$createType17 = settings$0.Settings.createFrom;
const $$createType18 = $Create.Array($Create.Any);
const $$createType19 = $models.WorldPrayerCitySummary.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = geonames$0.City.createFrom;
const $$createType22 = $Create.Array($$createType21);
