// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Service schedules prayer reminders
 */
export class Service {

    /** Creates a new Service instance. */
    constructor($$source: Partial<Service> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Service instance from a string or object.
     */
    static createFrom($$source: any = {}): Service {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Service($$parsedSource as Partial<Service>);
    }
}
