// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DashboardSettings controls dashboard widgets and presentation.
 */
export class DashboardSettings {
    "showClock": boolean;

    /**
     * "digital" or "analog"
     */
    "clockType": string;
    "digitalClockFormat": string;
    "digitalClockCustom": string;
    "analogClockSize": number;
    "showAllClockHours": boolean;

    /** Creates a new DashboardSettings instance. */
    constructor($$source: Partial<DashboardSettings> = {}) {
        if (!("showClock" in $$source)) {
            this["showClock"] = false;
        }
        if (!("clockType" in $$source)) {
            this["clockType"] = "";
        }
        if (!("digitalClockFormat" in $$source)) {
            this["digitalClockFormat"] = "";
        }
        if (!("digitalClockCustom" in $$source)) {
            this["digitalClockCustom"] = "";
        }
        if (!("analogClockSize" in $$source)) {
            this["analogClockSize"] = 0;
        }
        if (!("showAllClockHours" in $$source)) {
            this["showAllClockHours"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DashboardSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): DashboardSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DashboardSettings($$parsedSource as Partial<DashboardSettings>);
    }
}

/**
 * LocationSettings stores location configuration
 */
export class LocationSettings {
    "autoDetect": boolean;

    /**
     * "list" or "custom"
     */
    "inputMode": string;
    "city": string;
    "country": string;
    "latitude": number;
    "longitude": number;
    "elevation": number;
    "timezone": string;

    /** Creates a new LocationSettings instance. */
    constructor($$source: Partial<LocationSettings> = {}) {
        if (!("autoDetect" in $$source)) {
            this["autoDetect"] = false;
        }
        if (!("inputMode" in $$source)) {
            this["inputMode"] = "";
        }
        if (!("city" in $$source)) {
            this["city"] = "";
        }
        if (!("country" in $$source)) {
            this["country"] = "";
        }
        if (!("latitude" in $$source)) {
            this["latitude"] = 0;
        }
        if (!("longitude" in $$source)) {
            this["longitude"] = 0;
        }
        if (!("elevation" in $$source)) {
            this["elevation"] = 0;
        }
        if (!("timezone" in $$source)) {
            this["timezone"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocationSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): LocationSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocationSettings($$parsedSource as Partial<LocationSettings>);
    }
}

/**
 * NotificationSettings stores all notification preferences
 */
export class NotificationSettings {
    "style": NotificationStyle;
    "playAdhan": boolean;

    /**
     * 0.0 to 1.0
     */
    "adhanVolume": number;
    "prayers": PerPrayerNotification;

    /** Creates a new NotificationSettings instance. */
    constructor($$source: Partial<NotificationSettings> = {}) {
        if (!("style" in $$source)) {
            this["style"] = NotificationStyle.$zero;
        }
        if (!("playAdhan" in $$source)) {
            this["playAdhan"] = false;
        }
        if (!("adhanVolume" in $$source)) {
            this["adhanVolume"] = 0;
        }
        if (!("prayers" in $$source)) {
            this["prayers"] = (new PerPrayerNotification());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotificationSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): NotificationSettings {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("prayers" in $$parsedSource) {
            $$parsedSource["prayers"] = $$createField3_0($$parsedSource["prayers"]);
        }
        return new NotificationSettings($$parsedSource as Partial<NotificationSettings>);
    }
}

/**
 * NotificationStyle defines how notifications are shown
 */
export enum NotificationStyle {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NotificationNative = "native",
    NotificationWindow = "window",
};

/**
 * PerPrayerNotification holds notification settings per prayer
 */
export class PerPrayerNotification {
    "fajr": PrayerNotificationSetting;
    "sunrise": PrayerNotificationSetting;
    "zuhr": PrayerNotificationSetting;
    "asr": PrayerNotificationSetting;
    "maghrib": PrayerNotificationSetting;
    "isha": PrayerNotificationSetting;

    /** Creates a new PerPrayerNotification instance. */
    constructor($$source: Partial<PerPrayerNotification> = {}) {
        if (!("fajr" in $$source)) {
            this["fajr"] = (new PrayerNotificationSetting());
        }
        if (!("sunrise" in $$source)) {
            this["sunrise"] = (new PrayerNotificationSetting());
        }
        if (!("zuhr" in $$source)) {
            this["zuhr"] = (new PrayerNotificationSetting());
        }
        if (!("asr" in $$source)) {
            this["asr"] = (new PrayerNotificationSetting());
        }
        if (!("maghrib" in $$source)) {
            this["maghrib"] = (new PrayerNotificationSetting());
        }
        if (!("isha" in $$source)) {
            this["isha"] = (new PrayerNotificationSetting());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PerPrayerNotification instance from a string or object.
     */
    static createFrom($$source: any = {}): PerPrayerNotification {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fajr" in $$parsedSource) {
            $$parsedSource["fajr"] = $$createField0_0($$parsedSource["fajr"]);
        }
        if ("sunrise" in $$parsedSource) {
            $$parsedSource["sunrise"] = $$createField1_0($$parsedSource["sunrise"]);
        }
        if ("zuhr" in $$parsedSource) {
            $$parsedSource["zuhr"] = $$createField2_0($$parsedSource["zuhr"]);
        }
        if ("asr" in $$parsedSource) {
            $$parsedSource["asr"] = $$createField3_0($$parsedSource["asr"]);
        }
        if ("maghrib" in $$parsedSource) {
            $$parsedSource["maghrib"] = $$createField4_0($$parsedSource["maghrib"]);
        }
        if ("isha" in $$parsedSource) {
            $$parsedSource["isha"] = $$createField5_0($$parsedSource["isha"]);
        }
        return new PerPrayerNotification($$parsedSource as Partial<PerPrayerNotification>);
    }
}

/**
 * PrayerNotificationSetting controls reminder for a single prayer
 */
export class PrayerNotificationSetting {
    "enabled": boolean;

    /**
     * minutes before prayer to remind
     */
    "beforeMinutes": number;

    /**
     * minutes after prayer to auto-dismiss
     */
    "afterMinutes": number;

    /** Creates a new PrayerNotificationSetting instance. */
    constructor($$source: Partial<PrayerNotificationSetting> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("beforeMinutes" in $$source)) {
            this["beforeMinutes"] = 0;
        }
        if (!("afterMinutes" in $$source)) {
            this["afterMinutes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrayerNotificationSetting instance from a string or object.
     */
    static createFrom($$source: any = {}): PrayerNotificationSetting {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PrayerNotificationSetting($$parsedSource as Partial<PrayerNotificationSetting>);
    }
}

/**
 * PrayerOffsets for each prayer in minutes
 */
export class PrayerOffsets {
    "fajr": number;
    "sunrise": number;
    "zuhr": number;
    "asr": number;
    "maghrib": number;
    "isha": number;

    /** Creates a new PrayerOffsets instance. */
    constructor($$source: Partial<PrayerOffsets> = {}) {
        if (!("fajr" in $$source)) {
            this["fajr"] = 0;
        }
        if (!("sunrise" in $$source)) {
            this["sunrise"] = 0;
        }
        if (!("zuhr" in $$source)) {
            this["zuhr"] = 0;
        }
        if (!("asr" in $$source)) {
            this["asr"] = 0;
        }
        if (!("maghrib" in $$source)) {
            this["maghrib"] = 0;
        }
        if (!("isha" in $$source)) {
            this["isha"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrayerOffsets instance from a string or object.
     */
    static createFrom($$source: any = {}): PrayerOffsets {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PrayerOffsets($$parsedSource as Partial<PrayerOffsets>);
    }
}

/**
 * PrayerSettings holds prayer calculation configuration
 */
export class PrayerSettings {
    "method": string;
    "asrMethod": string;
    "offsets": PrayerOffsets;
    "customFajrAngle": number;
    "customIshaAngle": number;
    "customMaghribDuration": number;

    /** Creates a new PrayerSettings instance. */
    constructor($$source: Partial<PrayerSettings> = {}) {
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("asrMethod" in $$source)) {
            this["asrMethod"] = "";
        }
        if (!("offsets" in $$source)) {
            this["offsets"] = (new PrayerOffsets());
        }
        if (!("customFajrAngle" in $$source)) {
            this["customFajrAngle"] = 0;
        }
        if (!("customIshaAngle" in $$source)) {
            this["customIshaAngle"] = 0;
        }
        if (!("customMaghribDuration" in $$source)) {
            this["customMaghribDuration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrayerSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): PrayerSettings {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("offsets" in $$parsedSource) {
            $$parsedSource["offsets"] = $$createField2_0($$parsedSource["offsets"]);
        }
        return new PrayerSettings($$parsedSource as Partial<PrayerSettings>);
    }
}

/**
 * PrayerTimesSettings controls how the monthly prayer-times page is shown.
 */
export class PrayerTimesSettings {
    /**
     * "table" or "calendar"
     */
    "viewMode": string;

    /**
     * "gregorian", "hijri", or "side-by-side"
     */
    "calendarSystem": string;

    /**
     * render Hijri numerals using Arabic-Indic digits
     */
    "useArabicIndicDigits": boolean;

    /** Creates a new PrayerTimesSettings instance. */
    constructor($$source: Partial<PrayerTimesSettings> = {}) {
        if (!("viewMode" in $$source)) {
            this["viewMode"] = "";
        }
        if (!("calendarSystem" in $$source)) {
            this["calendarSystem"] = "";
        }
        if (!("useArabicIndicDigits" in $$source)) {
            this["useArabicIndicDigits"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrayerTimesSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): PrayerTimesSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PrayerTimesSettings($$parsedSource as Partial<PrayerTimesSettings>);
    }
}

/**
 * Settings is the root configuration struct
 */
export class Settings {
    "location": LocationSettings;
    "prayer": PrayerSettings;
    "notification": NotificationSettings;
    "dashboard": DashboardSettings;
    "prayerTimes": PrayerTimesSettings;
    "worldPrayer": WorldPrayerSettings;

    /**
     * "light", "dark", "system"
     */
    "theme": string;
    "themePreset": string;

    /**
     * "en", "id", etc
     */
    "language": string;
    "autoStart": boolean;
    "autoCheckUpdates": boolean;

    /**
     * "toggle-window", "open-menu", or "none"
     */
    "trayLeftClick": string;

    /**
     * -2 to +2 days
     */
    "hijriDateOffset": number;

    /**
     * "12h" or "24h"
     */
    "timeFormat": string;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("location" in $$source)) {
            this["location"] = (new LocationSettings());
        }
        if (!("prayer" in $$source)) {
            this["prayer"] = (new PrayerSettings());
        }
        if (!("notification" in $$source)) {
            this["notification"] = (new NotificationSettings());
        }
        if (!("dashboard" in $$source)) {
            this["dashboard"] = (new DashboardSettings());
        }
        if (!("prayerTimes" in $$source)) {
            this["prayerTimes"] = (new PrayerTimesSettings());
        }
        if (!("worldPrayer" in $$source)) {
            this["worldPrayer"] = (new WorldPrayerSettings());
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("themePreset" in $$source)) {
            this["themePreset"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("autoStart" in $$source)) {
            this["autoStart"] = false;
        }
        if (!("autoCheckUpdates" in $$source)) {
            this["autoCheckUpdates"] = false;
        }
        if (!("trayLeftClick" in $$source)) {
            this["trayLeftClick"] = "";
        }
        if (!("hijriDateOffset" in $$source)) {
            this["hijriDateOffset"] = 0;
        }
        if (!("timeFormat" in $$source)) {
            this["timeFormat"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType6;
        const $$createField4_0 = $$createType7;
        const $$createField5_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("location" in $$parsedSource) {
            $$parsedSource["location"] = $$createField0_0($$parsedSource["location"]);
        }
        if ("prayer" in $$parsedSource) {
            $$parsedSource["prayer"] = $$createField1_0($$parsedSource["prayer"]);
        }
        if ("notification" in $$parsedSource) {
            $$parsedSource["notification"] = $$createField2_0($$parsedSource["notification"]);
        }
        if ("dashboard" in $$parsedSource) {
            $$parsedSource["dashboard"] = $$createField3_0($$parsedSource["dashboard"]);
        }
        if ("prayerTimes" in $$parsedSource) {
            $$parsedSource["prayerTimes"] = $$createField4_0($$parsedSource["prayerTimes"]);
        }
        if ("worldPrayer" in $$parsedSource) {
            $$parsedSource["worldPrayer"] = $$createField5_0($$parsedSource["worldPrayer"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * WorldPrayerCity stores a saved city entry for the world prayer times page.
 */
export class WorldPrayerCity {
    "id": number;
    "name": string;
    "countryCode": string;
    "admin1": string;
    "latitude": number;
    "longitude": number;
    "elevation": number;
    "timezone": string;
    "label": string;

    /** Creates a new WorldPrayerCity instance. */
    constructor($$source: Partial<WorldPrayerCity> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("countryCode" in $$source)) {
            this["countryCode"] = "";
        }
        if (!("admin1" in $$source)) {
            this["admin1"] = "";
        }
        if (!("latitude" in $$source)) {
            this["latitude"] = 0;
        }
        if (!("longitude" in $$source)) {
            this["longitude"] = 0;
        }
        if (!("elevation" in $$source)) {
            this["elevation"] = 0;
        }
        if (!("timezone" in $$source)) {
            this["timezone"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorldPrayerCity instance from a string or object.
     */
    static createFrom($$source: any = {}): WorldPrayerCity {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorldPrayerCity($$parsedSource as Partial<WorldPrayerCity>);
    }
}

/**
 * WorldPrayerSettings controls the world prayer times view.
 */
export class WorldPrayerSettings {
    "cities": WorldPrayerCity[];

    /**
     * "name", "offset", "current-time", "next-prayer"
     */
    "sortBy": string;

    /** Creates a new WorldPrayerSettings instance. */
    constructor($$source: Partial<WorldPrayerSettings> = {}) {
        if (!("cities" in $$source)) {
            this["cities"] = [];
        }
        if (!("sortBy" in $$source)) {
            this["sortBy"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorldPrayerSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): WorldPrayerSettings {
        const $$createField0_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cities" in $$parsedSource) {
            $$parsedSource["cities"] = $$createField0_0($$parsedSource["cities"]);
        }
        return new WorldPrayerSettings($$parsedSource as Partial<WorldPrayerSettings>);
    }
}

// Private type creation functions
const $$createType0 = PerPrayerNotification.createFrom;
const $$createType1 = PrayerNotificationSetting.createFrom;
const $$createType2 = PrayerOffsets.createFrom;
const $$createType3 = LocationSettings.createFrom;
const $$createType4 = PrayerSettings.createFrom;
const $$createType5 = NotificationSettings.createFrom;
const $$createType6 = DashboardSettings.createFrom;
const $$createType7 = PrayerTimesSettings.createFrom;
const $$createType8 = WorldPrayerSettings.createFrom;
const $$createType9 = WorldPrayerCity.createFrom;
const $$createType10 = $Create.Array($$createType9);
