// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * HijriDate represents a date in the Islamic (Hijri) calendar
 */
export class HijriDate {
    "day": number;
    "month": number;
    "year": number;

    /** Creates a new HijriDate instance. */
    constructor($$source: Partial<HijriDate> = {}) {
        if (!("day" in $$source)) {
            this["day"] = 0;
        }
        if (!("month" in $$source)) {
            this["month"] = 0;
        }
        if (!("year" in $$source)) {
            this["year"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HijriDate instance from a string or object.
     */
    static createFrom($$source: any = {}): HijriDate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HijriDate($$parsedSource as Partial<HijriDate>);
    }
}
