// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ReminderInfo contains data passed to the reminder window
 */
export class ReminderInfo {
    "prayerName": string;
    "state": WindowState;
    "minutesLeft": number;
    "offsetMinutes": number;
    "triggerId": number;
    "live": boolean;
    "notification"?: ReminderNotificationSettings | null;

    /** Creates a new ReminderInfo instance. */
    constructor($$source: Partial<ReminderInfo> = {}) {
        if (!("prayerName" in $$source)) {
            this["prayerName"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = WindowState.$zero;
        }
        if (!("minutesLeft" in $$source)) {
            this["minutesLeft"] = 0;
        }
        if (!("offsetMinutes" in $$source)) {
            this["offsetMinutes"] = 0;
        }
        if (!("triggerId" in $$source)) {
            this["triggerId"] = 0;
        }
        if (!("live" in $$source)) {
            this["live"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReminderInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ReminderInfo {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("notification" in $$parsedSource) {
            $$parsedSource["notification"] = $$createField6_0($$parsedSource["notification"]);
        }
        return new ReminderInfo($$parsedSource as Partial<ReminderInfo>);
    }
}

/**
 * ReminderNotificationSettings is a snapshot of reminder-related settings.
 */
export class ReminderNotificationSettings {
    "persistentReminder": boolean;
    "autoDismissSeconds": number;
    "autoDismissAfterAdhan": boolean;
    "playAdhan": boolean;
    "adhanVolume": number;
    "alwaysOnTop": boolean;
    "useNativeNotification": boolean;
    "nativeNotificationSticky": boolean;
    "useNativeDialog": boolean;

    /** Creates a new ReminderNotificationSettings instance. */
    constructor($$source: Partial<ReminderNotificationSettings> = {}) {
        if (!("persistentReminder" in $$source)) {
            this["persistentReminder"] = false;
        }
        if (!("autoDismissSeconds" in $$source)) {
            this["autoDismissSeconds"] = 0;
        }
        if (!("autoDismissAfterAdhan" in $$source)) {
            this["autoDismissAfterAdhan"] = false;
        }
        if (!("playAdhan" in $$source)) {
            this["playAdhan"] = false;
        }
        if (!("adhanVolume" in $$source)) {
            this["adhanVolume"] = 0;
        }
        if (!("alwaysOnTop" in $$source)) {
            this["alwaysOnTop"] = false;
        }
        if (!("useNativeNotification" in $$source)) {
            this["useNativeNotification"] = false;
        }
        if (!("nativeNotificationSticky" in $$source)) {
            this["nativeNotificationSticky"] = false;
        }
        if (!("useNativeDialog" in $$source)) {
            this["useNativeDialog"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReminderNotificationSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ReminderNotificationSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReminderNotificationSettings($$parsedSource as Partial<ReminderNotificationSettings>);
    }
}

export class Service {

    /** Creates a new Service instance. */
    constructor($$source: Partial<Service> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Service instance from a string or object.
     */
    static createFrom($$source: any = {}): Service {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Service($$parsedSource as Partial<Service>);
    }
}

/**
 * WindowState represents the state of the reminder window
 */
export enum WindowState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateBefore = "before",
    StateOnTime = "ontime",
    StateAfter = "after",
};

// Private type creation functions
const $$createType0 = ReminderNotificationSettings.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
