// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class City {
    "id": number;
    "name": string;
    "countryCode": string;
    "admin1": string;
    "latitude": number;
    "longitude": number;
    "elevation": number;
    "timezone": string;
    "label": string;

    /** Creates a new City instance. */
    constructor($$source: Partial<City> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("countryCode" in $$source)) {
            this["countryCode"] = "";
        }
        if (!("admin1" in $$source)) {
            this["admin1"] = "";
        }
        if (!("latitude" in $$source)) {
            this["latitude"] = 0;
        }
        if (!("longitude" in $$source)) {
            this["longitude"] = 0;
        }
        if (!("elevation" in $$source)) {
            this["elevation"] = 0;
        }
        if (!("timezone" in $$source)) {
            this["timezone"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new City instance from a string or object.
     */
    static createFrom($$source: any = {}): City {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new City($$parsedSource as Partial<City>);
    }
}

export class DataInfo {
    "source": string;
    "lastUpdated": string;

    /** Creates a new DataInfo instance. */
    constructor($$source: Partial<DataInfo> = {}) {
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("lastUpdated" in $$source)) {
            this["lastUpdated"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DataInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DataInfo($$parsedSource as Partial<DataInfo>);
    }
}
