// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Location holds geographic location data
 */
export class Location {
    "city": string;
    "country": string;
    "latitude": number;
    "longitude": number;
    "elevation": number;
    "timezone": string;

    /** Creates a new Location instance. */
    constructor($$source: Partial<Location> = {}) {
        if (!("city" in $$source)) {
            this["city"] = "";
        }
        if (!("country" in $$source)) {
            this["country"] = "";
        }
        if (!("latitude" in $$source)) {
            this["latitude"] = 0;
        }
        if (!("longitude" in $$source)) {
            this["longitude"] = 0;
        }
        if (!("elevation" in $$source)) {
            this["elevation"] = 0;
        }
        if (!("timezone" in $$source)) {
            this["timezone"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Location instance from a string or object.
     */
    static createFrom($$source: any = {}): Location {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Location($$parsedSource as Partial<Location>);
    }
}
