// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * DaySchedule holds the full set of prayer times for a day
 */
export class DaySchedule {
    "date": string;
    "fajr": time$0.Time;
    "sunrise": time$0.Time;
    "zuhr": time$0.Time;
    "asr": time$0.Time;
    "maghrib": time$0.Time;
    "isha": time$0.Time;
    "isNormal": boolean;

    /** Creates a new DaySchedule instance. */
    constructor($$source: Partial<DaySchedule> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("fajr" in $$source)) {
            this["fajr"] = null;
        }
        if (!("sunrise" in $$source)) {
            this["sunrise"] = null;
        }
        if (!("zuhr" in $$source)) {
            this["zuhr"] = null;
        }
        if (!("asr" in $$source)) {
            this["asr"] = null;
        }
        if (!("maghrib" in $$source)) {
            this["maghrib"] = null;
        }
        if (!("isha" in $$source)) {
            this["isha"] = null;
        }
        if (!("isNormal" in $$source)) {
            this["isNormal"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DaySchedule instance from a string or object.
     */
    static createFrom($$source: any = {}): DaySchedule {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DaySchedule($$parsedSource as Partial<DaySchedule>);
    }
}

/**
 * NextPrayerInfo holds info about the upcoming prayer
 */
export class NextPrayerInfo {
    "name": string;
    "time": time$0.Time;

    /** Creates a new NextPrayerInfo instance. */
    constructor($$source: Partial<NextPrayerInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NextPrayerInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): NextPrayerInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NextPrayerInfo($$parsedSource as Partial<NextPrayerInfo>);
    }
}
