// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DaySchedule holds the full set of prayer times for a day
 */
export class DaySchedule {
    "date": string;
    "fajr": string;
    "sunrise": string;
    "zuhr": string;
    "asr": string;
    "maghrib": string;
    "isha": string;
    "isNormal": boolean;

    /** Creates a new DaySchedule instance. */
    constructor($$source: Partial<DaySchedule> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("fajr" in $$source)) {
            this["fajr"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("sunrise" in $$source)) {
            this["sunrise"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("zuhr" in $$source)) {
            this["zuhr"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("asr" in $$source)) {
            this["asr"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("maghrib" in $$source)) {
            this["maghrib"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("isha" in $$source)) {
            this["isha"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("isNormal" in $$source)) {
            this["isNormal"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DaySchedule instance from a string or object.
     */
    static createFrom($$source: any = {}): DaySchedule {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DaySchedule($$parsedSource as Partial<DaySchedule>);
    }
}

/**
 * NextPrayerInfo holds info about the upcoming prayer
 */
export class NextPrayerInfo {
    "name": string;
    "time": string;

    /** Creates a new NextPrayerInfo instance. */
    constructor($$source: Partial<NextPrayerInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NextPrayerInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): NextPrayerInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NextPrayerInfo($$parsedSource as Partial<NextPrayerInfo>);
    }
}

/**
 * PrayerOffsets stores minute-based offsets for each prayer
 */
export class PrayerOffsets {
    "fajr": number;
    "sunrise": number;
    "zuhr": number;
    "asr": number;
    "maghrib": number;
    "isha": number;

    /** Creates a new PrayerOffsets instance. */
    constructor($$source: Partial<PrayerOffsets> = {}) {
        if (!("fajr" in $$source)) {
            this["fajr"] = 0;
        }
        if (!("sunrise" in $$source)) {
            this["sunrise"] = 0;
        }
        if (!("zuhr" in $$source)) {
            this["zuhr"] = 0;
        }
        if (!("asr" in $$source)) {
            this["asr"] = 0;
        }
        if (!("maghrib" in $$source)) {
            this["maghrib"] = 0;
        }
        if (!("isha" in $$source)) {
            this["isha"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrayerOffsets instance from a string or object.
     */
    static createFrom($$source: any = {}): PrayerOffsets {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PrayerOffsets($$parsedSource as Partial<PrayerOffsets>);
    }
}
