// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as prayer$0 from "../prayer/models.js";

/**
 * Config controls the optional online reference. Empty Provider preserves
 * AlAdhan for existing settings. Method applies only to AlAdhan (-1 is regional
 * selection); CityID selects a published myQuran city timetable.
 */
export class Config {
    "provider": string;
    "cityId": string;
    "cityName": string;
    "regionId": string;
    "regionName": string;
    "enabled": boolean;
    "onStartup": boolean;
    "intervalHours": number;
    "method": number;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("cityId" in $$source)) {
            this["cityId"] = "";
        }
        if (!("cityName" in $$source)) {
            this["cityName"] = "";
        }
        if (!("regionId" in $$source)) {
            this["regionId"] = "";
        }
        if (!("regionName" in $$source)) {
            this["regionName"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("onStartup" in $$source)) {
            this["onStartup"] = false;
        }
        if (!("intervalHours" in $$source)) {
            this["intervalHours"] = 0;
        }
        if (!("method" in $$source)) {
            this["method"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * ProviderInfo describes the configuration and capabilities of a timetable provider.
 * Localized labels and explanatory copy remain in the frontend.
 */
export class ProviderInfo {
    "id": string;
    "name": string;
    "source": string;
    "url": string;
    "regional": boolean;
    "timezones": string[];
    "locationType": string;
    "hasLocationList": boolean;
    "hasRegionSelector": boolean;

    /** Creates a new ProviderInfo instance. */
    constructor($$source: Partial<ProviderInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("regional" in $$source)) {
            this["regional"] = false;
        }
        if (!("timezones" in $$source)) {
            this["timezones"] = [];
        }
        if (!("locationType" in $$source)) {
            this["locationType"] = "";
        }
        if (!("hasLocationList" in $$source)) {
            this["hasLocationList"] = false;
        }
        if (!("hasRegionSelector" in $$source)) {
            this["hasRegionSelector"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderInfo {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("timezones" in $$parsedSource) {
            $$parsedSource["timezones"] = $$createField5_0($$parsedSource["timezones"]);
        }
        return new ProviderInfo($$parsedSource as Partial<ProviderInfo>);
    }
}

export class Status {
    "enabled": boolean;
    "syncing": boolean;
    "todayActive": boolean;
    "lastSync": string;
    "nextSync": string;
    "lastError": string;
    "source": string;
    "apiEndpoint": string;
    "methodName": string;
    "fromDate": string;
    "throughDate": string;
    "todayOffsets": prayer$0.PrayerOffsets;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("syncing" in $$source)) {
            this["syncing"] = false;
        }
        if (!("todayActive" in $$source)) {
            this["todayActive"] = false;
        }
        if (!("lastSync" in $$source)) {
            this["lastSync"] = "";
        }
        if (!("nextSync" in $$source)) {
            this["nextSync"] = "";
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("apiEndpoint" in $$source)) {
            this["apiEndpoint"] = "";
        }
        if (!("methodName" in $$source)) {
            this["methodName"] = "";
        }
        if (!("fromDate" in $$source)) {
            this["fromDate"] = "";
        }
        if (!("throughDate" in $$source)) {
            this["throughDate"] = "";
        }
        if (!("todayOffsets" in $$source)) {
            this["todayOffsets"] = (new prayer$0.PrayerOffsets());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        const $$createField11_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("todayOffsets" in $$parsedSource) {
            $$parsedSource["todayOffsets"] = $$createField11_0($$parsedSource["todayOffsets"]);
        }
        return new Status($$parsedSource as Partial<Status>);
    }
}

/**
 * TimetableCity identifies a published city timetable, not a GPS calculation.
 */
export class TimetableCity {
    "id": string;
    "lokasi": string;

    /** Creates a new TimetableCity instance. */
    constructor($$source: Partial<TimetableCity> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("lokasi" in $$source)) {
            this["lokasi"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimetableCity instance from a string or object.
     */
    static createFrom($$source: any = {}): TimetableCity {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TimetableCity($$parsedSource as Partial<TimetableCity>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = prayer$0.PrayerOffsets.createFrom;
